name: Sync

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:piecezyz/zyztest.git
          destination-repo: git@gitee.com:zhou-yuanzhi/zyztest.git
	  cache_path: /github/workspace/hub-mirror-cache
	  force_update: true
	  debug: true
