name: Sync

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/piecezyz
          dst: gitee/zhou-yuanzhi
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          static_list: "zyztest"
          clone_style: "ssh"
